# Generated by Django 2.1.2 on 2018-11-28 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_barang', models.URLField()),
                ('nama_barang', models.CharField(blank=True, max_length=200, null=True)),
                ('harga_asli', models.IntegerField(blank=True, null=True)),
                ('harga_jual', models.IntegerField(blank=True, null=True)),
                ('is_produk_unggulan', models.BooleanField(default=False, verbose_name='Produk Unggulan')),
                ('dilihat', models.CharField(blank=True, max_length=100, null=True)),
                ('terjual', models.CharField(blank=True, max_length=100, null=True)),
                ('informasi_produk', models.TextField(blank=True, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('last_upload', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_gambar', models.URLField()),
                ('barang_induk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_gambar_barang', to='tokopedia.Good')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_toko', models.URLField()),
                ('nama_toko', models.CharField(blank=True, max_length=200, null=True)),
                ('slogan_toko', models.TextField(blank=True, null=True)),
                ('quote_toko', models.TextField(blank=True, null=True)),
                ('gambar_toko', models.URLField(blank=True, null=True)),
                ('cover_toko', models.URLField(blank=True, null=True)),
                ('terjual', models.CharField(blank=True, max_length=50, null=True)),
                ('follower', models.CharField(blank=True, max_length=50, null=True)),
                ('kecepatan', models.CharField(blank=True, max_length=50, null=True)),
                ('reputasi', models.CharField(blank=True, max_length=50, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='toko_induk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_barang', to='tokopedia.Shop'),
        ),
    ]
