# Generated by Django 2.1.2 on 2018-11-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='id_toko',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
