# Generated by Django 2.1.2 on 2018-11-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0002_shop_id_toko'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='kecepatan',
        ),
        migrations.AddField(
            model_name='shop',
            name='kecepatan_1_bulan_order_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='kecepatan_1_bulan_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='kecepatan_1_tahun_order_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='kecepatan_1_tahun_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='kecepatan_3_bulan_order_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='kecepatan_3_bulan_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
