# Generated by Django 2.1.2 on 2018-11-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0003_auto_20181129_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='follower_int',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='jumlah_barang',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='terjual_int',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
