# Generated by Django 2.1.2 on 2018-11-30 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0004_auto_20181130_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_etalase', models.IntegerField(blank=True, null=True)),
                ('nama_etalase', models.CharField(blank=True, max_length=150, null=True)),
                ('alias_etalase', models.CharField(blank=True, max_length=150, null=True)),
                ('uri_etalase', models.URLField(blank=True, max_length=150, null=True)),
                ('jumlah_produk', models.IntegerField(blank=True, null=True)),
                ('toko_induk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_etalase', to='tokopedia.Shop')),
            ],
        ),
    ]
