# Generated by Django 2.1.2 on 2018-11-30 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0006_auto_20181130_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan_id', models.IntegerField(blank=True, null=True)),
                ('catatan_judul', models.CharField(blank=True, max_length=150, null=True)),
                ('catatan_posisi', models.IntegerField(blank=True, null=True)),
                ('catatan_uri', models.URLField(blank=True, max_length=150, null=True)),
                ('catatan_last_update', models.CharField(blank=True, max_length=150, null=True)),
                ('toko_induk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_catatan', to='tokopedia.Shop')),
            ],
        ),
    ]
