# Generated by Django 2.1.2 on 2018-11-30 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0007_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showcase',
            old_name='alias_etalase',
            new_name='etalase_alias',
        ),
        migrations.RenameField(
            model_name='showcase',
            old_name='id_etalase',
            new_name='etalase_id',
        ),
        migrations.RenameField(
            model_name='showcase',
            old_name='jumlah_produk',
            new_name='etalase_jumlah_produk',
        ),
        migrations.RenameField(
            model_name='showcase',
            old_name='nama_etalase',
            new_name='etalase_nama',
        ),
        migrations.RenameField(
            model_name='showcase',
            old_name='uri_etalase',
            new_name='etalase_url',
        ),
    ]
