# Generated by Django 2.1.2 on 2018-11-30 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0008_auto_20181130_1314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Showcase',
            new_name='Etalase',
        ),
    ]
