# Generated by Django 2.1.2 on 2018-11-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0009_auto_20181130_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodimage',
            old_name='link_gambar',
            new_name='gambar_url',
        ),
    ]
