# Generated by Django 2.1.2 on 2018-11-30 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0011_auto_20181130_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='kecepatan_1_bulan_order_count',
            new_name='toko_1_bulan_order_count',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='kecepatan_1_bulan_speed',
            new_name='toko_1_bulan_speed',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='kecepatan_1_tahun_order_count',
            new_name='toko_1_tahun_order_count',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='kecepatan_1_tahun_speed',
            new_name='toko_1_tahun_speed',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='kecepatan_3_bulan_order_count',
            new_name='toko_3_bulan_order_count',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='kecepatan_3_bulan_speed',
            new_name='toko_3_bulan_speed',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='cover_toko',
            new_name='toko_cover',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='follower',
            new_name='toko_follower',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='follower_int',
            new_name='toko_follower_int',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='gambar_toko',
            new_name='toko_gambar',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='id_toko',
            new_name='toko_id',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='jumlah_barang',
            new_name='toko_jumlah_barang',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='nama_toko',
            new_name='toko_nama',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='quote_toko',
            new_name='toko_quote',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='reputasi_badge',
            new_name='toko_reputasi_badge_url',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='reputasi_level',
            new_name='toko_reputasi_level',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='reputasi_score',
            new_name='toko_reputasi_score',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='slogan_toko',
            new_name='toko_slogan',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='terjual',
            new_name='toko_terjual',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='terjual_int',
            new_name='toko_terjual_int',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='link_toko',
            new_name='toko_url',
        ),
    ]
