# Generated by Django 2.1.2 on 2018-11-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0012_auto_20181130_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='toko_1_tahun_order_count',
            new_name='toko_12_bulan_order_count',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='toko_1_tahun_speed',
            new_name='toko_12_bulan_speed',
        ),
    ]
