# Generated by Django 2.1.2 on 2018-11-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0013_auto_20181130_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='barang_gambar_utama',
            field=models.URLField(blank=True, null=True),
        ),
    ]
