# Generated by Django 2.1.2 on 2018-11-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0014_good_barang_gambar_utama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('department_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='toko_is_gold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='toko_is_official',
            field=models.BooleanField(default=False),
        ),
    ]
