# Generated by Django 2.1.2 on 2018-11-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0016_good_barang_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='barang_child',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='barang_diskon_expired',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='barang_diskon_harga_asli',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='barang_diskon_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='barang_diskon_start',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='barang_is_preorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='good',
            name='barang_jumlah_kurir',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='barang_jumlah_ulasan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='barang_kondisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='barang_minimal_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='barang_parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='barang_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='barang_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='barang_stok',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
