# Generated by Django 2.1.2 on 2018-11-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0017_auto_20181130_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='barang_rating_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jumlah Pemberi Bintang'),
        ),
        migrations.AddField(
            model_name='good',
            name='barang_transaksi_gagal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='good',
            name='barang_transaksi_sukses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='toko_kota',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='toko_lokasi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='barang_dilihat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='barang_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jumlah Pemberi Bintang'),
        ),
        migrations.AlterField(
            model_name='good',
            name='barang_terjual',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
