# Generated by Django 2.1.2 on 2018-11-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0018_auto_20181130_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='barang_dilihat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
