# Generated by Django 2.1.2 on 2018-11-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0019_auto_20181130_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='barang_dilihat_int',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
