# Generated by Django 2.1.2 on 2018-11-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0021_auto_20181201_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='toko_url_full',
        ),
        migrations.AddField(
            model_name='good',
            name='barang_url_full',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
    ]
