# Generated by Django 2.1.2 on 2018-11-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0022_auto_20181201_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='barang_jumlah_ulasan',
        ),
        migrations.AlterField(
            model_name='good',
            name='barang_rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jumlah Bintang'),
        ),
    ]
