# Generated by Django 2.1.2 on 2018-12-01 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0023_auto_20181201_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='barang_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kategori_barang', to='tokopedia.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='barang_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department_barang', to='tokopedia.Department'),
            preserve_default=False,
        ),
    ]
