# Generated by Django 2.1.2 on 2018-12-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0027_good_last_scrapped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='toko_follower_int',
            field=models.IntegerField(blank=True, default=-1, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='toko_terjual_int',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
