# Generated by Django 2.1.5 on 2019-02-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0028_auto_20181204_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='toko_follower_int',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
